(function(root){
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>Number(v).toLocaleString('en-US',{maximumFractionDigits:2});
function summarize(groups){return groups.map((s,index)=>({s,index,r:root.FormCalc.calculate(s)}));}
function book(groups,method){const rows=summarize(groups),invalid=rows.filter(g=>g.r.errors.length);if(invalid.length)return{html:`<div class="book-error"><h2>合併計算書尚未完成</h2><p>請先修正：${invalid.map(g=>`第 ${g.index+1} 組「${esc(g.s.name)}」`).join('、')}的輸入數值。所有有效與未通過組別皆會納入，不會略過 N.G. 結果。</p></div>`,invalid};
const failed=rows.filter(g=>!g.r.pass).length;return{invalid:[],html:`<section class="book-cover"><span class="eyebrow">COMPLETE CALCULATION BOOK</span><h2>樓板模板完整計算書</h2><p>共 ${groups.length} 組　｜　通過 ${groups.length-failed} 組　｜　未通過 ${failed} 組<br>編製時間：${new Date().toLocaleString('zh-TW',{hour12:false})}</p><p>本計算書依輸入組別順序彙整。各組的材料尺寸、載重、梁分析模式、撓度限值與支撐條件獨立計算，所有 N.G. 結果照實列入。顯示值最多保留小數點後 2 位，判定採完整精度。</p><h3>組別目錄與檢核總表</h3><div class="book-table-wrap"><table><thead><tr><th>組別／模板名稱</th><th>樓板厚度<br>cm</th><th>總載重<br>tf/m²</th><th>板材</th><th>角材</th><th>貫材</th><th>支撐</th></tr></thead><tbody>${rows.map(g=>`<tr><td><a href="#book-group-${g.index+1}">${g.index+1}. ${esc(g.s.name||'未命名')}</a></td><td>${fmt(g.s.slabThickness)}</td><td>${fmt(g.r.q)}</td>${g.r.members.map(m=>`<td>${m.pass?'OK':'N.G.'}</td>`).join('')}<td>${g.r.support.pass?'OK':'N.G.'}</td></tr>`).join('')}</tbody></table></div></section>${rows.map(g=>`<section class="book-group" id="book-group-${g.index+1}"><div class="book-group-label">第 ${g.index+1} 組 / 共 ${groups.length} 組　·　${esc(g.s.name||'未命名')}</div>${root.FormReport.build(g.s,g.r,g.index===rows.length-1?method:'')}</section>`).join('')}`};}
root.FormGroups={summarize,book};if(typeof module!=='undefined')module.exports=root.FormGroups;
if(typeof document==='undefined')return;
const key='formwork-studio-groups-v1';let groups=[state()],active=0,storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&Array.isArray(saved.groups)&&saved.groups.length&&saved.groups.every(s=>s&&typeof s==='object'&&!Array.isArray(s))){groups=saved.groups.map(s=>{const out={...FormCalc.defaults};for(const k of Object.keys(out))if(k in s)out[k]=s[k];return out;});active=Number.isInteger(saved.active)&&saved.active>=0&&saved.active<groups.length?saved.active:0;}}catch{storageOK=false;}
function loadGroup(){for(const [k,v]of Object.entries(groups[active])){const el=document.getElementById(k==='support'?'supportType':k);if(el)el.value=v??'';}}
function save(){try{localStorage.setItem(key,JSON.stringify({groups,active}));storageOK=true;}catch{storageOK=false;}document.getElementById('draft-status').textContent=storageOK?'各組獨立保留輸入；草稿已儲存在此瀏覽器，重新開啟可繼續編輯。':'此瀏覽器無法儲存草稿；本次開啟仍可使用多組計算，請於關閉前匯出計算書。';}
const originalRender=render;let compiled;
render=function(){groups[active]=state();originalRender();save();const summary=summarize(groups);document.getElementById('group-count').textContent=`${groups.length} 組`;document.getElementById('group-list').innerHTML=summary.map(g=>`<button type="button" data-group="${g.index}" aria-pressed="${g.index===active}" class="group-chip ${g.index===active?'selected':''}"><span>${g.index+1}. ${esc(g.s.name||'未命名')}</span><small>${g.r.errors.length?'輸入待完成':g.r.pass?'OK':'N.G.'}</small></button>`).join('');document.getElementById('delete-group').disabled=groups.length===1;document.getElementById('group-status').textContent=`正在編輯第 ${active+1} 組「${groups[active].name||'未命名'}」。切換組別會自動保留目前輸入；新增組別使用原始預設，複製本組沿用目前條件。`;compiled=book(groups,document.querySelector('.method details>div').innerHTML);document.getElementById('report').innerHTML=compiled.html;document.getElementById('print-all').disabled=!!compiled.invalid.length;document.getElementById('word-all').disabled=!!compiled.invalid.length;document.getElementById('word-one').disabled=!!FormCalc.calculate(groups[active]).errors.length;};
document.getElementById('group-list').addEventListener('click',e=>{const btn=e.target.closest('[data-group]');if(!btn)return;groups[active]=state();active=Number(btn.dataset.group);loadGroup();render();});
function nextName(){let i=groups.length+1;while(groups.some(g=>g.name==='Form'+String(i).padStart(2,'0')))i++;return 'Form'+String(i).padStart(2,'0');}
function add(copy){groups[active]=state();const name=nextName();groups.push({...copy?groups[active]:FormCalc.defaults,name});active=groups.length-1;loadGroup();render();document.getElementById('name').focus();}
document.getElementById('add-group').onclick=()=>add(false);document.getElementById('copy-group').onclick=()=>add(true);
document.getElementById('delete-group').onclick=()=>{if(groups.length<2)return;if(!confirm(`刪除第 ${active+1} 組「${groups[active].name||'未命名'}」？此動作無法復原。`))return;groups.splice(active,1);active=Math.min(active,groups.length-1);loadGroup();render();};
document.getElementById('reset').textContent='本組恢復原始案例';document.getElementById('reset').onclick=()=>{if(!confirm('將目前組別恢復為原始案例？其他組別不受影響。'))return;fill();};
document.getElementById('print-all').onclick=()=>{render();if(!compiled.invalid.length)window.print();};
document.getElementById('print').onclick=()=>{render();const s=groups[active],r=FormCalc.calculate(s);if(r.errors.length)return;document.getElementById('report').innerHTML=FormReport.build(s,r,document.querySelector('.method details>div').innerHTML);window.print();};window.addEventListener('afterprint',()=>{document.getElementById('report').innerHTML=compiled.html;});
async function exportWord(all){render();const s=groups[active],r=FormCalc.calculate(s);if(all?compiled.invalid.length:r.errors.length)return;const btn=document.getElementById(all?'word-all':'word-one'),label=btn.textContent;btn.disabled=true;btn.textContent='正在製作 Word…';try{await FormWord.download(all?compiled.html:FormReport.build(s,r,document.querySelector('.method details>div').innerHTML),all?'樓板模板完整計算書':s.name+'計算書');}catch(e){alert('Word 匯出失敗：'+e.message);}finally{btn.textContent=label;render();}}
document.getElementById('word-all').onclick=()=>exportWord(true);
document.getElementById('word-one').onclick=()=>exportWord(false);
loadGroup();render();
})(typeof window!=='undefined'?window:globalThis);
