(function(root){
const n=(v,p=2)=>Number(v).toLocaleString('en-US',{minimumFractionDigits:Math.min(p,2),maximumFractionDigits:Math.min(p,2)});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const line=(formula,substitution,result,unit='')=>`<div class="calc-line"><div class="formula">${formula}</div><div class="substitution">= ${substitution}</div><div class="calculated">= <strong>${result}</strong> ${unit}</div></div>`;
const step=(title,content)=>{const layout={'1. 斷面性質':'calc-columns calc-three','2. 鋼管斷面性質':'calc-columns calc-three','3. 最大彎矩與剪力':'calc-columns calc-two','4. 彎曲應力與剪應力檢核':'calc-columns calc-two calc-stress','1. 樓板自重':'calc-columns calc-two','2. 靜載重與總面載重':'calc-columns calc-two'}[title]||'';return `<section class="calc-step ${layout}"><h4>${title}</h4>${content}</section>`;};
const check=(label,v,a,unit)=>`<p class="check-line ${v<=a?'check-ok':'check-ng'}">${label}：${n(v,6)} ${v<=a?'≤':'>'} ${n(a,6)} ${unit} → <strong>${v<=a?'OK':'N.G.'}</strong>；使用率 = ${n(v,6)} / ${n(a,6)} × 100% = ${n(v/a*100,2)}%</p>`;
function member(s,m,i){const name=['板材','角材','貫材'][i],E=s['e'+i],simple=s['beam'+i]==='simple',two=s['beam'+i]==='continuous2',B=n(m.b),h=n(m.h),L=n(m.L),w=n(m.w,6),I=n(m.I,6);let out=`<article class="report-block detailed-member"><h3>${['二','三','四'][i]}、${name}設計與檢核</h3><p>分析模式：${simple?'簡支梁，均布載重':two?'兩跨連續梁，等跨、等 EI，全跨均布載重':'三跨連續梁，等跨、等 EI，全跨均布載重'}。<br>b = ${B} cm；h = ${h} cm；L = ${n(s['l'+i])} × 100 = ${L} cm（每一跨長度）。<br>E = ${n(E,0)} kgf/cm²；Fb = ${n(s['fb'+i])} kgf/cm²；Fv = ${n(s['fv'+i])} kgf/cm²。</p>`;
out+=step('1. 斷面性質',line('A = b × h',`${B} × ${h}`,n(m.A,6),'cm²')+line('I = b × h³ / 12',`${B} × ${h}³ / 12`,I,'cm⁴')+line('Z = b × h² / 6',`${B} × ${h}² / 6`,n(m.Z,6),'cm³'));
out+=step('2. 面載重換算線載重',`<p>分攤寬度 B = ${i===0?'板帶寬 b / 100':i===1?'角材間距 L1':'貫材間距 L2'} = ${n(m.width)} m。<br>1 tf = 1,000 kgf，1 m = 100 cm，故換算係數為 1,000 / 100 = 10。</p>`+line('w = q × B × 1,000 / 100',`${n(s._q,6)} × ${n(m.width)} × 1,000 / 100`,w,'kgf/cm'));
const mDiv=simple||two?8:10;
let forces=line(simple?'Mmax = wL² / 8':`|M|max = wL² / ${mDiv}`,`${w} × ${L}² / ${mDiv}`,n(m.M,6),'kgf·cm')+line(simple?'Vmax = wL / 2':two?'|V|max = 5wL / 8':'|V|max = 3wL / 5',simple?`${w} × ${L} / 2`:two?`5 × ${w} × ${L} / 8`:`3 × ${w} × ${L} / 5`,n(m.V,6),'kgf');
if(two)forces+=`<p>支點彎矩 [MA, MB, MC] = [0, −wL²/8, 0]<br>= [0, −${n(m.M)}, 0] kgf·cm。<br>最大正彎矩 = 9wL²/128 = 9 × ${w} × ${L}² / 128 = ${n(9*m.w*m.L*m.L/128)} kgf·cm。<br>端支點反力 = 3wL/8 = ${n(3*m.w*m.L/8)} kgf；內支點反力 = 5wL/4 = ${n(5*m.w*m.L/4)} kgf（僅列示梁本身反力，不傳遞放大至下層）。</p>`;
else if(!simple)forces+=`<p>支點彎矩 [MA, MB, MC, MD] = [0, −wL²/10, −wL²/10, 0]<br>= [0, −${n(m.M)}, −${n(m.M)}, 0] kgf·cm。<br>最大正彎矩 = 2wL²/25 = 2 × ${w} × ${L}² / 25 = ${n(.08*m.w*m.L*m.L)} kgf·cm。<br>端支點反力 = 2wL/5 = ${n(.4*m.w*m.L)} kgf；內支點反力 = 11wL/10 = ${n(1.1*m.w*m.L)} kgf（僅列示梁本身反力，不傳遞放大至下層）。</p>`;
out+=step('3. 最大彎矩與剪力',forces);
out+=step('4. 彎曲應力與剪應力檢核',line('fb = Mmax / Z',`${n(m.M,6)} / ${n(m.Z,6)}`,n(m.fb,6),'kgf/cm²')+check('fb ≤ Fb',m.fb,s['fb'+i],'kgf/cm²')+line('fv = 1.5Vmax / A',`1.5 × ${n(m.V,6)} / ${n(m.A,6)}`,n(m.fv,6),'kgf/cm²')+check('fv ≤ Fv',m.fv,s['fv'+i],'kgf/cm²'));
let def='';if(simple){def=line('δmax = 5wL⁴ / (384EI)',`5 × ${w} × ${L}⁴ / (384 × ${n(E,0)} × ${I})`,n(m.def,6),'cm')+`<p>最大撓度位置 x = L/2 = ${n(m.L/2)} cm。</p>`;}else{def=`<p>最大撓度速查：δmax ≈ ${two?'0.00542':'0.00688'}wL⁴/(EI)，外跨距外端約 ${two?'0.42154':'0.44604'}L。以下採彎矩積分與轉角零點計算完整精度。</p><p>各跨以左端為 x = 0。給定兩端彎矩 Ma、Mb：<br>Ra = wL/2 + (Mb − Ma)/L<br>M(x) = Ma + Ra·x − wx²/2<br>C = −[MaL²/2 + RaL³/6 − wL⁴/24]/L<br>y(x) = [Ma·x²/2 + Ra·x³/6 − wx⁴/24 + C·x]/(EI)<br>令 y′(x) = [Ma·x + Ra·x²/2 − wx³/6 + C]/(EI) = 0，求各跨內極值點並與端點比較，取 |y| 最大值。</p>`;
m.spans.forEach((p,j)=>{def+=`<div class="span-calculation"><h5>第 ${j+1} 跨</h5><p>Ma = ${n(p.a,6)}、Mb = ${n(p.b,6)} kgf·cm。</p>`+line('Ra = wL/2 + (Mb − Ma)/L',`${w} × ${L}/2 + [${n(p.b,6)} − (${n(p.a,6)})]/${L}`,n(p.R,6),'kgf')+line('C = −[MaL²/2 + RaL³/6 − wL⁴/24]/L',`−[(${n(p.a,6)}) × ${L}²/2 + ${n(p.R,6)} × ${L}³/6 − ${w} × ${L}⁴/24]/${L}`,n(p.C,6),'kgf·cm²')+`<p>解 (${n(p.a,6)})x + (${n(p.R,6)})x²/2 − (${w})x³/6 + (${n(p.C,6)}) = 0，取跨內控制位置 x = ${n(p.x,6)} cm。</p>`+line('δ = |y(x)|',`|[(${n(p.a,6)}) × ${n(p.x,6)}²/2 + (${n(p.R,6)}) × ${n(p.x,6)}³/6 − (${w}) × ${n(p.x,6)}⁴/24 + (${n(p.C,6)}) × ${n(p.x,6)}] / (${n(E,0)} × ${I})|`,n(p.def,6),'cm')+'</div>';});def+=`<p><strong>δmax = max(${m.spans.map(p=>n(p.def,6)).join(', ')}) = ${n(m.def,6)} cm。</strong>極值位置由轉角零點數值求解，計算保留完整精度。</p>`;}
def+=s.defMode==='absolute'?`<p>容許撓度 δallow = ${n(m.limit,6)} cm（使用者自訂固定值）。</p>`:line('δallow = L/n',`${L} / ${n(s.ratio,2)}`,n(m.limit,6),'cm');out+=step('5. 最大撓度與容許值檢核',def+check('δmax ≤ δallow',m.def,m.limit,'cm'));return out+`<p class="member-verdict"><strong>${name}檢核結果：${m.pass?'OK':'N.G.'}</strong></p></article>`;}
function support(s,r){let p=r.support;let out='<article class="report-block detailed-member"><h3>五、支撐軸壓設計與檢核</h3>';out+=step('1. 支柱負擔軸力',`<p>每支承點分攤面積 = L2 × L3 = ${n(s.l1)} × ${n(s.l2)} = ${n(s.l1*s.l2)} m²。<br>支撐軸力採總面載重乘分攤面積，不加計連續梁反力放大。</p>`+line('P = q × L2 × L3',`${n(r.q,6)} × ${n(s.l1)} × ${n(s.l2)}`,n(p.P,6),'tf'));
if(s.support==='tube'){let d=s.diameter-2*s.thick,D=n(s.diameter),t=n(s.thick);out+=step('2. 鋼管斷面性質',line('d = D − 2t',`${D} − 2 × ${t}`,n(d),'cm')+line('A = π(D² − d²)/4',`π × (${D}² − ${n(d)}²)/4`,n(p.A,6),'cm²')+line('I = π(D⁴ − d⁴)/64',`π × (${D}⁴ − ${n(d)}⁴)/64`,n(p.I,6),'cm⁴')+line('Z = 2I/D',`2 × ${n(p.I,6)} / ${D}`,n(p.Z,6),'cm³')+line('r = √(I/A)',`√(${n(p.I,6)} / ${n(p.A,6)})`,n(p.r,6),'cm'));
out+=step('3. 有效長度與細長比',`<p>鋼材 E = ${n(s.es,0)} kgf/cm²；Fy = ${n(s.fy,0)} kgf/cm²；無側撐長 Lb = ${n(s.lb)} cm；K = ${n(s.k)}。</p>`+line('λ = KLb/r',`${n(s.k)} × ${n(s.lb)} / ${n(p.r,6)}`,n(p.slender,6))+`<p>細長比篩檢：${n(p.slender,6)} ${p.slenderOK?'≤':'>'} 200 → <strong>${p.slenderOK?'OK':'N.G.'}</strong>。</p>`+line('Cc = √(2π²E/Fy)',`√(2 × π² × ${n(s.es,0)} / ${n(s.fy,0)})`,n(p.Cc,6)));
let fa=`<p>採用分支：λ = ${n(p.slender)} ${p.slender<p.Cc?'&lt;':'≥'} Cc = ${n(p.Cc)}。</p>`;
if(p.slender<p.Cc)fa+=line('FS = 5/3 + 3λ/(8Cc) − λ³/(8Cc³)',`5/3 + 3 × ${n(p.slender,6)}/(8 × ${n(p.Cc,6)}) − ${n(p.slender,6)}³/(8 × ${n(p.Cc,6)}³)`,n(p.FS,6))+line('Fa = [1 − λ²/(2Cc²)]Fy/FS',`[1 − ${n(p.slender,6)}²/(2 × ${n(p.Cc,6)}²)] × ${n(s.fy,0)} / ${n(p.FS,6)}`,n(p.Fa,6),'kgf/cm²');else fa+=line('Fa = 12π²E/(23λ²)',`12 × π² × ${n(s.es,0)} / (23 × ${n(p.slender,6)}²)`,n(p.Fa,6),'kgf/cm²');out+=step('4. 容許壓應力與容許承載力',fa+line('Pallow = Fa × A / 1,000',`${n(p.Fa,6)} × ${n(p.A,6)} / 1,000`,n(p.capacity,6),'tf'));
}else out+=step('2. 容許承載力',`<p>採用使用者輸入之每支承點容許承載力 Pallow = ${n(p.capacity,6)} tf；須與實際高度、配置及廠商資料一致。</p>`);
return out+step('軸力檢核',check('P ≤ Pallow',p.P,p.capacity,'tf')+`<p><strong>支撐綜合判定：${p.pass?'OK':'N.G.'}</strong>（鋼管模式同時檢核細長比）。</p>` )+'</article>';}
function build(s,r,method=''){s={...s,_q:r.q};return `<div class="report-heading"><span class="eyebrow">04 / DETAILED CALCULATION SHEET</span><h2>樓板模板詳細設計計算書</h2><p>模板：${esc(s.name)}　｜　版次：${esc(s.version)}　｜　設計人：${esc(s.designer)}<br>計算時間：${new Date().toLocaleString('zh-TW',{hour12:false})}<br>單位採 kgf、tf、cm；所有計算顯示值最多保留小數點後 2 位，其餘四捨五入；計算與合格判定採完整精度，避免逐步捨入誤差。</p></div><article class="report-block"><h3>一、樓板厚度、靜載重與總載重</h3>${step('1. 樓板自重',`<p>輸入樓板厚度 H = ${n(s.slabThickness,2)} cm；混凝土單位重 γc = 2.4 tf/m³。</p>`+line('H(m) = H(cm) / 100',`${n(s.slabThickness,2)} / 100`,n(s.slabThickness/100),'m')+line('qRC = H(m) × γc',`${n(s.slabThickness/100)} × 2.4`,n(r.concreteDead,6),'tf/m²'))}${step('2. 靜載重與總面載重',line('qD = qRC + q其他',`${n(r.concreteDead,6)} + ${n(s.extraDead,6)}`,n(r.dead,6),'tf/m²')+line('q = qD + qL + qI',`${n(r.dead,6)} + ${n(s.live,6)} + ${n(s.impact,6)}`,n(r.q,6),'tf/m²')+`<p>其他靜載重 = ${n(s.extraDead)} tf/m²；活載重 = ${n(s.live)} tf/m²；衝擊載重 = ${n(s.impact)} tf/m²。<br>衝擊載重為直接加計的面載重，非百分比。其他靜載重未輸入時為 0。</p>`)}<p>L1 = ${n(s.l0)} m；L2 = ${n(s.l1)} m；L3 = ${n(s.l2)} m。支柱配置 = ${n(s.l2*100)} × ${n(s.l1*100)} cm。</p></article>${r.members.map((m,i)=>member(s,m,i)).join('')}${support(s,r)}<article class="report-block"><h3>六、計算結果彙整</h3><table><thead><tr><th>構件</th><th>控制使用率</th><th>判定</th></tr></thead><tbody>${r.members.map((m,i)=>`<tr><td>${['板材','角材','貫材'][i]}</td><td>${n(Math.max(...m.ratios)*100,2)}%</td><td>${m.pass?'OK':'N.G.'}</td></tr>`).join('')}<tr><td>支撐</td><td>軸力 ${n(r.support.ratio*100,2)}%</td><td>${r.support.pass?'OK':'N.G.'}</td></tr></tbody></table><p><strong>所列構件綜合結果：${r.pass?'通過':'不通過'}。</strong></p></article>${method?`<article class="report-block"><h3>模型與適用範圍</h3>${method}</article>`:''}`;}
root.FormReport={build};if(typeof module!=='undefined')module.exports=root.FormReport;
})(typeof window!=='undefined'?window:globalThis);
