(function(root){
const xml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const has=(n,c)=>(n.cls||'').split(' ').includes(c);
function text(n){return typeof n==='string'?n:n.tag==='br'?'\n':(n.children||[]).map(text).join('');}
function p(value,style='Normal'){let runs=String(value).split('\n').map((line,i)=>(i?'<w:r><w:br/></w:r>':'')+'<w:r><w:t xml:space="preserve">'+xml(line)+'</w:t></w:r>').join('');return `<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr>${runs}</w:p>`;}
function table(rows){const count=Math.max(...rows.map(r=>r.length)),width=Math.floor(10318/count);return `<w:tbl><w:tblPr><w:tblW w:w="10318" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders>${['top','left','bottom','right','insideH','insideV'].map(x=>`<w:${x} w:val="single" w:sz="4" w:color="D9D9D9"/>`).join('')}</w:tblBorders><w:tblCellMar><w:top w:w="55" w:type="dxa"/><w:left w:w="85" w:type="dxa"/><w:bottom w:w="55" w:type="dxa"/><w:right w:w="85" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>${Array.from({length:count},()=>`<w:gridCol w:w="${width}"/>`).join('')}</w:tblGrid>${rows.map(row=>`<w:tr><w:trPr><w:cantSplit/></w:trPr>${row.map(cell=>`<w:tc><w:tcPr><w:tcW w:w="${width}" w:type="dxa"/><w:vAlign w:val="top"/></w:tcPr>${cell||p('')}</w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>`;}
function formula(n,compact=false){const lines=(n.children||[]).filter(v=>typeof v!=='string').map(text);return p(lines.join(compact?' ':'\n'),'Formula');}
function walk(n){if(typeof n==='string')return n.trim()?p(n):'';const children=n.children||[];if(has(n,'eyebrow'))return '';if(has(n,'calc-line'))return formula(n,true);if(has(n,'book-group-label'))return p(text(n),'Group');if(has(n,'calc-columns')){const heading=children.filter(c=>c.tag==='h4').map(walk).join(''),rest=children.filter(c=>c.tag!=='h4'&&typeof c!=='string');if(has(n,'calc-stress')){return heading+table([[walk(rest[0])+walk(rest[1]),walk(rest[2])+walk(rest[3])]]);}const cols=has(n,'calc-three')?3:2;let out=heading,pending=[];const flush=()=>{while(pending.length)out+=table([pending.splice(0,cols)]);};for(const c of rest){if(has(c,'calc-line'))pending.push(formula(c,false));else{flush();out+=walk(c);}}flush();return out;}if(n.tag==='table'){let rows=[];function scan(t){if(t.tag==='tr'){rows.push((t.children||[]).filter(c=>c.tag==='td'||c.tag==='th').map(c=>p(text(c),t.children.some(c=>c.tag==='th')?'TableHead':'Normal')));}else for(const c of t.children||[])if(typeof c!=='string')scan(c);}scan(n);return table(rows);}if(/^h[1-6]$/.test(n.tag))return p(text(n),n.tag==='h2'?'Title':n.tag==='h3'?'Heading1':'Heading2');if(n.tag==='p')return p(text(n));return children.map(walk).join('');}
const header='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
function files(tree){let body=walk(tree);return{
'[Content_Types].xml':header+'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/></Types>',
'_rels/.rels':header+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
'word/_rels/document.xml.rels':header+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>',
'word/document.xml':header+`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="680" w:right="794" w:bottom="680" w:left="794" w:header="0" w:footer="0"/></w:sectPr></w:body></w:document>`,
'word/styles.xml':header+`<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Noto Sans CJK TC" w:hAnsi="Noto Sans CJK TC" w:eastAsia="Noto Sans CJK TC" w:cs="Noto Sans CJK TC"/><w:sz w:val="19"/><w:lang w:val="en-US" w:eastAsia="zh-TW"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:before="0" w:after="30" w:line="240" w:lineRule="exact"/><w:widowControl/></w:pPr></w:pPrDefault></w:docDefaults>${[['Normal',19],['Title',27],['Heading1',22],['Heading2',20],['Group',24],['Formula',19],['TableHead',19]].map(([name,size])=>`<w:style w:type="paragraph" w:styleId="${name}"><w:name w:val="${name}"/>${name!=='Normal'?'<w:basedOn w:val="Normal"/>':''}<w:pPr>${['Title','Heading1','Heading2','Group'].includes(name)?'<w:keepNext/><w:spacing w:before="60" w:after="35" w:line="240" w:lineRule="auto"/>':''}${name==='Formula'?'<w:spacing w:before="0" w:after="25" w:line="240" w:lineRule="exact"/>':''}</w:pPr><w:rPr><w:sz w:val="${size}"/>${['Title','Heading1','Heading2','Group','TableHead'].includes(name)?'<w:b/>':''}<w:color w:val="000000"/></w:rPr></w:style>`).join('')}</w:styles>`};}
const encoder=new TextEncoder();function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let j=0;j<8;j++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function zip(entries){const parts=[],central=[];let offset=0;function record(size){const a=new Uint8Array(size);return[a,new DataView(a.buffer)];}for(const [name,value]of Object.entries(entries)){const nameBytes=encoder.encode(name),data=value instanceof Uint8Array?value:encoder.encode(value),sum=crc(data);let [a,v]=record(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,sum,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,nameBytes.length,true);parts.push(a,nameBytes,data);let [c,d]=record(46);d.setUint32(0,0x02014b50,true);d.setUint16(4,20,true);d.setUint16(6,20,true);d.setUint16(8,0x800,true);d.setUint32(16,sum,true);d.setUint32(20,data.length,true);d.setUint32(24,data.length,true);d.setUint16(28,nameBytes.length,true);d.setUint32(42,offset,true);central.push(c,nameBytes);offset+=a.length+nameBytes.length+data.length;}const cdsize=central.reduce((s,a)=>s+a.length,0),[end,ev]=record(22);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,Object.keys(entries).length,true);ev.setUint16(10,Object.keys(entries).length,true);ev.setUint32(12,cdsize,true);ev.setUint32(16,offset,true);let result=new Uint8Array(offset+cdsize+22),pos=0;for(const a of [...parts,...central,end]){result.set(a,pos);pos+=a.length;}return result;}
function domTree(n){if(n.nodeType===3)return n.nodeValue;return{tag:n.tagName?.toLowerCase()||'div',cls:n.className||'',children:Array.from(n.childNodes||[]).filter(c=>c.nodeType===1||c.nodeType===3).map(domTree)};}
function withFont(tree,font){const entries=files(tree),data=new Uint8Array(font instanceof Uint8Array?font:new Uint8Array(font));for(let i=0;i<32;i++)data[i]^=0x11;entries['word/fonts/report.odttf']=data;entries['word/fontTable.xml']=header+'<w:fonts xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><w:font w:name="Noto Sans CJK TC"><w:family w:val="swiss"/><w:embedRegular r:id="font1" w:fontKey="{11111111-1111-1111-1111-111111111111}"/></w:font></w:fonts>';entries['word/_rels/fontTable.xml.rels']=header+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="font1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/font" Target="fonts/report.odttf"/></Relationships>';entries['word/_rels/document.xml.rels']=entries['word/_rels/document.xml.rels'].replace('</Relationships>','<Relationship Id="fontTable" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/></Relationships>');entries['[Content_Types].xml']=entries['[Content_Types].xml'].replace('</Types>','<Default Extension="odttf" ContentType="application/vnd.openxmlformats-officedocument.obfuscatedFont"/><Override PartName="/word/fontTable.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"/></Types>');return entries;}
let fontPromise;async function download(html,name){fontPromise=fontPromise||fetch('report-font.otf').then(r=>{if(!r.ok)throw Error('字型載入失敗，請重新嘗試匯出。');return r.arrayBuffer();}).catch(e=>{fontPromise=null;throw e;});const font=await fontPromise,doc=new DOMParser().parseFromString(html,'text/html'),bytes=zip(withFont(domTree(doc.body),font)),url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})),a=document.createElement('a');a.href=url;a.download=(name||'樓板模板計算書').replace(/[\\/:*?"<>|]/g,'_')+'.docx';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}

root.FormWord={files,zip,download,withFont};if(typeof module!=='undefined')module.exports=root.FormWord;
})(typeof window!=='undefined'?window:globalThis);
